security:
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider

  providers:
    fos_userbundle:
      id: fos_user.user_provider.username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      pattern: ^/
      user_checker: fos_user.user_checker
      logout:
        path: security_logout
        target: home
      custom_authenticators:
        - App\Security\FormLoginAuthenticator


      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
  # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  # - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  # - { path: ^/single_trick/[ ^/]+, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/update_tricks/[ ^/]+, roles: ROLE_USER }
  # - { path: ^/delete_trick/[ ^/]+, roles: ROLE_USER }
  # - { path: ^/create_account, roles: ROLE_USER  }
  # - { path: ^/forgot_password, roles: ROLE_USER  }
  # - { path: ^/reset_password, roles: ROLE_USER  }
  # - { path: ^/add_comment/[ ^/]+, roles: IS_AUTHENTICATED_ANONYMOUSLY }


when@test:
  security:
    password_hashers:
      App\Entity\User: 'auto'
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
